### ISSUE TITLE
[MINT-UI] Visualization shows several times same output

### ISSUE THREAD

**Issue by dgarijo** [mintproject/Dash#9]
Take the Flood Severity Index model, which only has 1 output and 1 execution only. When the visualization appears, the same movie appears 4 times:

![image](https://user-images.githubusercontent.com/1520666/73226336-8ee19d00-4124-11ea-912f-f00dc64212b5.png)

**Comment by mepearson** [comment]
This appears to have been fixed at some point - I am no longer seeing this effect.
